# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Python requirements required to build your documentation
python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt
    - requirements: docs/requirements.txt

# Optionally set the version of pip and its tools to be the same as the local
# development environment
build:
  tools:
    python: "3.11"
    nodejs: "18"

# Optionally give the set of commands that are needed to build your docs
# If you don't specify this, then the default commands are:
# - sphinx-build -b html docs/ docs/_build/html
build:
  commands:
    - sphinx-build -b html docs/ docs/_build/html 