name: nocturna-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-mock>=3.10.0
  - pytest-xdist>=3.3.1
  - pytest-timeout>=2.1.0
  - pytest-benchmark>=4.0.0
  - pytest-asyncio>=0.21.1
  - pytest-datadir>=1.4.1
  - pytest-regressions>=2.4.1
  - pytest-randomly>=3.12.0
  - hypothesis>=6.82.0
  - httpx>=0.24.1
  - locust>=2.15.1
  - bandit>=1.7.5
  - safety>=3.0.1
  - black>=23.7.0
  - flake8>=6.1.0
  - mypy>=1.5.1
  - sphinx>=7.1.2
  - sphinx-rtd-theme>=1.3.0
  - pre-commit>=3.3.3
  - pip:
    - git+https://github.com/astrorigin/pyswisseph.git