name: nocturna-base
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.10.0
  
  # Data handling
  - pandas>=2.0.0
  - pydantic>=2.0.0
  
  # System dependencies
  - pip>=23.0
  - setuptools>=68.0
  - wheel>=0.40.0
  
  # Essential tools
  - git
  - make
  
  # Pip dependencies (core library)
  - pip:
    - -e . 