name: nocturna-prod
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version (latest stable)
  - python=3.11
  
  # Minimal system dependencies
  - pip>=23.0
  - setuptools>=68.0
  - wheel>=0.40.0
  
  # Production database clients only
  - psycopg2>=2.9
  - redis-py>=4.5
  
  # Pip dependencies
  - pip:
    # Install package with API extras only (no dev/test)
    - nocturna-calculations[api] 